"""canonical_v2_schema_foundation

Revision ID: fd9910efb66e
Revises: 
Create Date: 2026-08-29 17:24:07.757826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fd9910efb66e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSchema("canonical_v2", if_not_exists=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), nullable=False),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('normalized_preferred_name', sa.Text(), nullable=True),
    sa.Column('name_status', sa.String(length=48), nullable=False),
    sa.Column('identity_status', sa.String(length=24), server_default=sa.text("'PROVISIONAL'"), nullable=False),
    sa.Column('query_eligible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("entity_kind IN ('FINANCIAL_PRODUCT', 'FUND_SHARE_CLASS', 'SALE_LOT', 'ORGANIZATION', 'INDEX')", name=op.f('ck_canonical_entities_kind_allowed')),
    sa.CheckConstraint("identity_status IN ('PROVISIONAL', 'VALIDATED', 'AMBIGUOUS', 'CONFLICT', 'RETIRED')", name=op.f('ck_canonical_entities_identity_status_allowed')),
    sa.CheckConstraint("name_status <> 'NO_AUTHORITATIVE_FAMILY_NAME' OR preferred_name IS NULL", name=op.f('ck_canonical_entities_missing_family_name_is_null')),
    sa.CheckConstraint("name_status IN ('AUTHORITATIVE', 'SOURCE_ONLY', 'NO_AUTHORITATIVE_FAMILY_NAME', 'UNKNOWN')", name=op.f('ck_canonical_entities_name_status_allowed')),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_canonical_entities')),
    sa.UniqueConstraint('entity_id', 'entity_kind', name='entity_kind_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_canonical_entities_kind', 'canonical_entities', ['entity_kind'], unique=False, schema='canonical_v2')
    op.create_index('ix_canonical_entities_normalized_name', 'canonical_entities', ['normalized_preferred_name'], unique=False, schema='canonical_v2')
    op.create_table('identifier_schemes',
    sa.Column('scheme_code', sa.String(length=48), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('default_namespace', sa.Text(), nullable=True),
    sa.Column('validation_pattern', sa.Text(), nullable=True),
    sa.Column('is_globally_unique', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('scheme_code', name=op.f('pk_identifier_schemes')),
    schema='canonical_v2'
    )
    op.create_table('metric_definitions',
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('canonical_field', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), server_default=sa.text("'NUMERIC'"), nullable=False),
    sa.Column('expected_unit', sa.String(length=32), nullable=True),
    sa.Column('expected_scale_basis', sa.String(length=32), nullable=True),
    sa.Column('cross_source_comparable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('filter_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("value_type IN ('NUMERIC', 'DATE')", name=op.f('ck_metric_definitions_value_type_allowed')),
    sa.PrimaryKeyConstraint('metric_code', name=op.f('pk_metric_definitions')),
    sa.UniqueConstraint('canonical_field', name=op.f('uq_metric_definitions_canonical_field')),
    schema='canonical_v2'
    )
    op.create_table('ontology_concepts',
    sa.Column('concept_iri', sa.Text(), nullable=False),
    sa.Column('concept_category', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('ontology_version', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('concept_iri', name=op.f('pk_ontology_concepts')),
    schema='canonical_v2'
    )
    op.create_index('ix_ontology_concepts_category', 'ontology_concepts', ['concept_category'], unique=False, schema='canonical_v2')
    op.create_table('product_types',
    sa.Column('product_type_code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('ontology_iri', sa.Text(), nullable=False),
    sa.CheckConstraint("product_type_code IN ('ETF', 'ETN', 'BOND', 'FUND')", name=op.f('ck_product_types_allowed_product_type')),
    sa.PrimaryKeyConstraint('product_type_code', name=op.f('pk_product_types')),
    sa.UniqueConstraint('ontology_iri', name=op.f('uq_product_types_ontology_iri')),
    schema='canonical_v2'
    )
    op.create_table('schema_versions',
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('component', name=op.f('pk_schema_versions')),
    schema='canonical_v2'
    )
    op.create_table('source_datasets',
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=True),
    sa.Column('schema_contract_version', sa.String(length=64), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('dataset_id', name=op.f('pk_source_datasets')),
    sa.UniqueConstraint('dataset_code', name=op.f('uq_source_datasets_dataset_code')),
    schema='canonical_v2'
    )
    op.create_table('dataset_snapshots',
    sa.Column('snapshot_id', sa.String(length=96), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('data_sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_row_count', sa.BigInteger(), nullable=False),
    sa.Column('accepted_row_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('quarantined_row_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'STAGED'"), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('row_count_reconciled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("reconciliation_status IN ('PENDING', 'PASSED', 'FAILED')", name=op.f('ck_dataset_snapshots_reconciliation_status_allowed')),
    sa.CheckConstraint("status <> 'READY' OR (reconciliation_status = 'PASSED' AND row_count_reconciled)", name=op.f('ck_dataset_snapshots_ready_requires_reconciliation')),
    sa.CheckConstraint("status IN ('STAGED', 'VALIDATING', 'READY', 'FAILED', 'RETIRED')", name=op.f('ck_dataset_snapshots_status_allowed')),
    sa.CheckConstraint('source_row_count >= 0 AND accepted_row_count >= 0 AND quarantined_row_count >= 0', name=op.f('ck_dataset_snapshots_nonnegative_counts')),
    sa.ForeignKeyConstraint(['dataset_id'], ['canonical_v2.source_datasets.dataset_id'], name=op.f('fk_dataset_snapshots_dataset_id_source_datasets')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_dataset_snapshots')),
    sa.UniqueConstraint('dataset_id', 'snapshot_date', 'data_sha256', name='dataset_snapshot_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_dataset_snapshots_dataset_date', 'dataset_snapshots', ['dataset_id', 'snapshot_date'], unique=False, schema='canonical_v2')
    op.create_table('entity_id_crosswalk',
    sa.Column('crosswalk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('v1_entity_id', sa.Text(), nullable=False),
    sa.Column('v1_entity_type', sa.String(length=64), nullable=False),
    sa.Column('v2_entity_id', sa.Text(), nullable=False),
    sa.Column('mapping_status', sa.String(length=24), nullable=False),
    sa.Column('mapping_basis', sa.Text(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("mapping_status IN ('EXACT', 'SPLIT', 'MERGED', 'AMBIGUOUS', 'REJECTED')", name=op.f('ck_entity_id_crosswalk_mapping_status_allowed')),
    sa.ForeignKeyConstraint(['v2_entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_entity_id_crosswalk_v2_entity_id_canonical_entities')),
    sa.PrimaryKeyConstraint('crosswalk_id', name=op.f('pk_entity_id_crosswalk')),
    sa.UniqueConstraint('v1_entity_id', 'v1_entity_type', 'v2_entity_id', name='entity_id_crosswalk_identity'),
    schema='canonical_v2'
    )
    op.create_table('financial_products',
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), server_default=sa.text("'FINANCIAL_PRODUCT'"), nullable=False),
    sa.Column('product_type_code', sa.String(length=16), nullable=False),
    sa.CheckConstraint("entity_kind = 'FINANCIAL_PRODUCT'", name=op.f('ck_financial_products_financial_product_kind')),
    sa.CheckConstraint("product_type_code IN ('ETF', 'ETN', 'BOND', 'FUND')", name=op.f('ck_financial_products_allowed_product_type')),
    sa.ForeignKeyConstraint(['product_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_financial_product_entity_kind'),
    sa.ForeignKeyConstraint(['product_type_code'], ['canonical_v2.product_types.product_type_code'], name=op.f('fk_financial_products_product_type_code_product_types')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_financial_products')),
    sa.UniqueConstraint('product_id', 'product_type_code', name='product_type_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_financial_products_type', 'financial_products', ['product_type_code'], unique=False, schema='canonical_v2')
    op.create_table('identifier_collision_cases',
    sa.Column('collision_case_id', sa.Text(), nullable=False),
    sa.Column('scheme_code', sa.String(length=48), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('candidate_entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'RESOLVED', 'REJECTED')", name=op.f('ck_identifier_collision_cases_status_allowed')),
    sa.ForeignKeyConstraint(['scheme_code'], ['canonical_v2.identifier_schemes.scheme_code'], name=op.f('fk_identifier_collision_cases_scheme_code_identifier_schemes')),
    sa.PrimaryKeyConstraint('collision_case_id', name=op.f('pk_identifier_collision_cases')),
    sa.UniqueConstraint('scheme_code', 'namespace', 'normalized_value', 'status', name='identifier_collision_state'),
    schema='canonical_v2'
    )
    op.create_table('indices',
    sa.Column('index_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), server_default=sa.text("'INDEX'"), nullable=False),
    sa.Column('resolution_status', sa.String(length=24), nullable=False),
    sa.CheckConstraint("entity_kind = 'INDEX'", name=op.f('ck_indices_index_kind')),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'AMBIGUOUS', 'UNRESOLVED')", name=op.f('ck_indices_resolution_status_allowed')),
    sa.ForeignKeyConstraint(['index_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_index_entity_kind'),
    sa.PrimaryKeyConstraint('index_id', name=op.f('pk_indices')),
    schema='canonical_v2'
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), server_default=sa.text("'ORGANIZATION'"), nullable=False),
    sa.Column('organization_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("entity_kind = 'ORGANIZATION'", name=op.f('ck_organizations_organization_kind')),
    sa.CheckConstraint("organization_type IN ('ASSET_MANAGER', 'ISSUER', 'TRUSTEE', 'DISTRIBUTOR', 'OTHER')", name=op.f('ck_organizations_organization_type_allowed')),
    sa.ForeignKeyConstraint(['organization_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_organization_entity_kind'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_organizations')),
    schema='canonical_v2'
    )
    op.create_table('bonds',
    sa.Column('bond_id', sa.Text(), nullable=False),
    sa.Column('product_type_code', sa.String(length=16), server_default=sa.text("'BOND'"), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.CheckConstraint("product_type_code = 'BOND'", name=op.f('ck_bonds_bond_product_type')),
    sa.ForeignKeyConstraint(['bond_id', 'product_type_code'], ['canonical_v2.financial_products.product_id', 'canonical_v2.financial_products.product_type_code'], name='fk_bond_product_type'),
    sa.PrimaryKeyConstraint('bond_id', name=op.f('pk_bonds')),
    schema='canonical_v2'
    )
    op.create_table('canonical_facts',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('subject_entity_id', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=96), nullable=False),
    sa.Column('fact_kind', sa.String(length=48), nullable=False),
    sa.Column('semantic_key', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.String(length=24), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("fact_kind IN ('ORGANIZATION_RELATION', 'INDEX_RELATION', 'CLASSIFICATION', 'METRIC')", name=op.f('ck_canonical_facts_fact_kind_allowed')),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'AMBIGUOUS', 'UNRESOLVED', 'CONFLICT')", name=op.f('ck_canonical_facts_resolution_status_allowed')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['canonical_v2.dataset_snapshots.snapshot_id'], name=op.f('fk_canonical_facts_snapshot_id_dataset_snapshots')),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_canonical_facts_subject_entity_id_canonical_entities')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_canonical_facts')),
    sa.UniqueConstraint('subject_entity_id', 'snapshot_id', 'fact_kind', 'semantic_key', name='canonical_fact_identity'),
    schema='canonical_v2'
    )
    op.create_table('exchange_traded_products',
    sa.Column('etp_id', sa.Text(), nullable=False),
    sa.Column('product_type_code', sa.String(length=16), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.CheckConstraint("product_type_code IN ('ETF', 'ETN')", name=op.f('ck_exchange_traded_products_etp_product_type')),
    sa.ForeignKeyConstraint(['etp_id', 'product_type_code'], ['canonical_v2.financial_products.product_id', 'canonical_v2.financial_products.product_type_code'], name='fk_etp_product_type'),
    sa.PrimaryKeyConstraint('etp_id', name=op.f('pk_exchange_traded_products')),
    schema='canonical_v2'
    )
    op.create_table('funds',
    sa.Column('fund_id', sa.Text(), nullable=False),
    sa.Column('product_type_code', sa.String(length=16), server_default=sa.text("'FUND'"), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.CheckConstraint("product_type_code = 'FUND'", name=op.f('ck_funds_fund_product_type')),
    sa.ForeignKeyConstraint(['fund_id', 'product_type_code'], ['canonical_v2.financial_products.product_id', 'canonical_v2.financial_products.product_type_code'], name='fk_fund_product_type'),
    sa.PrimaryKeyConstraint('fund_id', name=op.f('pk_funds')),
    schema='canonical_v2'
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transformer_version', sa.String(length=64), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK')", name=op.f('ck_ingestion_runs_status_allowed')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['canonical_v2.dataset_snapshots.snapshot_id'], name=op.f('fk_ingestion_runs_snapshot_id_dataset_snapshots')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_ingestion_runs')),
    schema='canonical_v2'
    )
    op.create_table('source_records',
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=96), nullable=False),
    sa.Column('source_primary_key', sa.Text(), nullable=False),
    sa.Column('source_row_number', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('quality_status', sa.String(length=32), server_default=sa.text("'UNVALIDATED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('source_row_number > 0', name=op.f('ck_source_records_positive_row_number')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['canonical_v2.dataset_snapshots.snapshot_id'], name=op.f('fk_source_records_snapshot_id_dataset_snapshots')),
    sa.PrimaryKeyConstraint('source_record_id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('snapshot_id', 'source_primary_key', name='source_record_identity'),
    sa.UniqueConstraint('snapshot_id', 'source_row_number', name='source_record_row'),
    schema='canonical_v2'
    )
    op.create_table('entity_aliases',
    sa.Column('alias_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_entity_aliases_entity_id_canonical_entities')),
    sa.ForeignKeyConstraint(['source_record_id'], ['canonical_v2.source_records.source_record_id'], name=op.f('fk_entity_aliases_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_id', 'normalized_alias', 'alias_type', name='entity_alias_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_entity_aliases_lookup', 'entity_aliases', ['normalized_alias'], unique=False, schema='canonical_v2')
    op.create_table('entity_classifications',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('concept_iri', sa.Text(), nullable=False),
    sa.Column('classification_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['concept_iri'], ['canonical_v2.ontology_concepts.concept_iri'], name=op.f('fk_entity_classifications_concept_iri_ontology_concepts')),
    sa.ForeignKeyConstraint(['entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_entity_classifications_entity_id_canonical_entities')),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_entity_classifications_fact_id_canonical_facts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_entity_classifications')),
    sa.UniqueConstraint('entity_id', 'classification_type', 'concept_iri', name='entity_classification_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_entity_classifications_concept', 'entity_classifications', ['concept_iri', 'classification_type'], unique=False, schema='canonical_v2')
    op.create_table('entity_identifiers',
    sa.Column('identifier_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('scheme_code', sa.String(length=48), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('resolution_status', sa.String(length=24), nullable=False),
    sa.Column('conflict_status', sa.String(length=24), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("conflict_status IN ('NONE', 'OPEN', 'RESOLVED')", name=op.f('ck_entity_identifiers_conflict_status_allowed')),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'AMBIGUOUS', 'UNRESOLVED')", name=op.f('ck_entity_identifiers_resolution_status_allowed')),
    sa.CheckConstraint("validation_status IN ('VALIDATED', 'UNVALIDATED', 'INVALID')", name=op.f('ck_entity_identifiers_validation_status_allowed')),
    sa.ForeignKeyConstraint(['entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_entity_identifiers_entity_id_canonical_entities')),
    sa.ForeignKeyConstraint(['scheme_code'], ['canonical_v2.identifier_schemes.scheme_code'], name=op.f('fk_entity_identifiers_scheme_code_identifier_schemes')),
    sa.ForeignKeyConstraint(['source_record_id'], ['canonical_v2.source_records.source_record_id'], name=op.f('fk_entity_identifiers_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('identifier_id', name=op.f('pk_entity_identifiers')),
    sa.UniqueConstraint('entity_id', 'scheme_code', 'namespace', 'normalized_value', name='entity_identifier_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_entity_identifiers_lookup', 'entity_identifiers', ['scheme_code', 'namespace', 'normalized_value'], unique=False, schema='canonical_v2')
    op.create_index('uq_entity_identifiers_validated_global', 'entity_identifiers', ['scheme_code', 'namespace', 'normalized_value'], unique=True, schema='canonical_v2', postgresql_where=sa.text("validation_status = 'VALIDATED' AND conflict_status = 'NONE'"))
    op.create_table('fact_conflict_cases',
    sa.Column('conflict_case_id', sa.Text(), nullable=False),
    sa.Column('subject_entity_id', sa.Text(), nullable=False),
    sa.Column('semantic_key', sa.Text(), nullable=False),
    sa.Column('candidate_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('winning_fact_id', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status <> 'RESOLVED' OR winning_fact_id IS NOT NULL", name=op.f('ck_fact_conflict_cases_resolved_has_winner')),
    sa.CheckConstraint("status IN ('OPEN', 'RESOLVED', 'UNRESOLVED', 'REJECTED')", name=op.f('ck_fact_conflict_cases_status_allowed')),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_fact_conflict_cases_subject_entity_id_canonical_entities')),
    sa.ForeignKeyConstraint(['winning_fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_fact_conflict_cases_winning_fact_id_canonical_facts')),
    sa.PrimaryKeyConstraint('conflict_case_id', name=op.f('pk_fact_conflict_cases')),
    schema='canonical_v2'
    )
    op.create_table('fund_share_classes',
    sa.Column('fund_share_class_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), server_default=sa.text("'FUND_SHARE_CLASS'"), nullable=False),
    sa.Column('parent_fund_id', sa.Text(), nullable=False),
    sa.Column('source_class_key', sa.Text(), nullable=False),
    sa.CheckConstraint("entity_kind = 'FUND_SHARE_CLASS'", name=op.f('ck_fund_share_classes_fund_share_class_kind')),
    sa.ForeignKeyConstraint(['fund_share_class_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_fund_share_class_entity_kind'),
    sa.ForeignKeyConstraint(['parent_fund_id'], ['canonical_v2.funds.fund_id'], name=op.f('fk_fund_share_classes_parent_fund_id_funds')),
    sa.PrimaryKeyConstraint('fund_share_class_id', name=op.f('pk_fund_share_classes')),
    sa.UniqueConstraint('parent_fund_id', 'source_class_key', name='fund_share_class_parent_key'),
    schema='canonical_v2'
    )
    op.create_index('ix_fund_share_classes_parent', 'fund_share_classes', ['parent_fund_id'], unique=False, schema='canonical_v2')
    op.create_table('identity_resolution_cases',
    sa.Column('resolution_case_id', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('raw_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_status', sa.String(length=24), nullable=False),
    sa.Column('resolved_entity_id', sa.Text(), nullable=True),
    sa.Column('resolution_rule', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("resolution_status <> 'RESOLVED' OR resolved_entity_id IS NOT NULL", name=op.f('ck_identity_resolution_cases_resolved_has_entity')),
    sa.CheckConstraint("resolution_status IN ('OPEN', 'RESOLVED', 'AMBIGUOUS', 'UNRESOLVED', 'REJECTED')", name=op.f('ck_identity_resolution_cases_resolution_status_allowed')),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_identity_resolution_cases_resolved_entity_id_canonical_entities')),
    sa.ForeignKeyConstraint(['source_record_id'], ['canonical_v2.source_records.source_record_id'], name=op.f('fk_identity_resolution_cases_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('resolution_case_id', name=op.f('pk_identity_resolution_cases')),
    schema='canonical_v2'
    )
    op.create_table('index_relations',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('subject_product_id', sa.Text(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('index_id', sa.Text(), nullable=False),
    sa.CheckConstraint("relation_type IN ('HAS_UNDERLYING_INDEX', 'TRACKS_INDEX', 'HAS_BENCHMARK')", name=op.f('ck_index_relations_relation_type_allowed')),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_index_relations_fact_id_canonical_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_id'], ['canonical_v2.indices.index_id'], name=op.f('fk_index_relations_index_id_indices')),
    sa.ForeignKeyConstraint(['subject_product_id'], ['canonical_v2.financial_products.product_id'], name=op.f('fk_index_relations_subject_product_id_financial_products')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_index_relations')),
    sa.UniqueConstraint('subject_product_id', 'relation_type', 'index_id', name='index_relation_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_index_relations_target', 'index_relations', ['index_id', 'relation_type'], unique=False, schema='canonical_v2')
    op.create_table('metric_observations',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('subject_entity_id', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=38, scale=15), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('scale_basis', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('comparability_status', sa.String(length=32), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.CheckConstraint("comparability_status <> 'COMPARABLE' OR (quality_status IN ('VALID', 'SOURCE_ZERO') AND unit IS NOT NULL AND scale_basis IS NOT NULL)", name=op.f('ck_metric_observations_comparable_requires_contract')),
    sa.CheckConstraint("comparability_status IN ('COMPARABLE', 'NOT_COMPARABLE', 'UNKNOWN')", name=op.f('ck_metric_observations_comparability_status_allowed')),
    sa.CheckConstraint("quality_status <> 'SOURCE_ZERO' OR (numeric_value = 0 AND date_value IS NULL)", name=op.f('ck_metric_observations_source_zero_is_numeric_zero')),
    sa.CheckConstraint("quality_status <> 'VALID' OR ((numeric_value IS NOT NULL) <> (date_value IS NOT NULL))", name=op.f('ck_metric_observations_valid_has_one_typed_value')),
    sa.CheckConstraint("quality_status IN ('VALID', 'SOURCE_ZERO', 'MISSING', 'NOT_APPLICABLE', 'INVALID', 'UNKNOWN')", name=op.f('ck_metric_observations_quality_status_allowed')),
    sa.CheckConstraint("quality_status NOT IN ('MISSING', 'NOT_APPLICABLE') OR (numeric_value IS NULL AND date_value IS NULL)", name=op.f('ck_metric_observations_missing_has_no_typed_value')),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_metric_observations_fact_id_canonical_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_code'], ['canonical_v2.metric_definitions.metric_code'], name=op.f('fk_metric_observations_metric_code_metric_definitions')),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['canonical_v2.canonical_entities.entity_id'], name=op.f('fk_metric_observations_subject_entity_id_canonical_entities')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_metric_observations')),
    schema='canonical_v2'
    )
    op.create_index('ix_metric_observations_metric_numeric', 'metric_observations', ['metric_code', 'numeric_value'], unique=False, schema='canonical_v2')
    op.create_index('ix_metric_observations_subject_metric_date', 'metric_observations', ['subject_entity_id', 'metric_code', 'observed_on'], unique=False, schema='canonical_v2')
    op.create_table('organization_relations',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('subject_product_id', sa.Text(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint("relation_type IN ('MANAGED_BY', 'ISSUED_BY', 'HAS_TRUSTEE')", name=op.f('ck_organization_relations_relation_type_allowed')),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_organization_relations_fact_id_canonical_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['canonical_v2.organizations.organization_id'], name=op.f('fk_organization_relations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subject_product_id'], ['canonical_v2.financial_products.product_id'], name=op.f('fk_organization_relations_subject_product_id_financial_products')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_organization_relations')),
    sa.UniqueConstraint('subject_product_id', 'relation_type', 'organization_id', name='organization_relation_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_organization_relations_target', 'organization_relations', ['organization_id', 'relation_type'], unique=False, schema='canonical_v2')
    op.create_table('quarantine_records',
    sa.Column('quarantine_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=96), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
    sa.Column('source_row_number', sa.BigInteger(), nullable=False),
    sa.Column('source_primary_key', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'REVIEWED', 'RESOLVED', 'REJECTED')", name=op.f('ck_quarantine_records_status_allowed')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['canonical_v2.ingestion_runs.run_id'], name=op.f('fk_quarantine_records_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['canonical_v2.dataset_snapshots.snapshot_id'], name=op.f('fk_quarantine_records_snapshot_id_dataset_snapshots')),
    sa.PrimaryKeyConstraint('quarantine_id', name=op.f('pk_quarantine_records')),
    sa.UniqueConstraint('snapshot_id', 'source_row_number', name='quarantine_source_row'),
    schema='canonical_v2'
    )
    op.create_table('sale_lots',
    sa.Column('sale_lot_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), server_default=sa.text("'SALE_LOT'"), nullable=False),
    sa.Column('bond_id', sa.Text(), nullable=False),
    sa.Column('trading_market_raw', sa.Text(), nullable=False),
    sa.Column('information_date', sa.Date(), nullable=False),
    sa.Column('lot_sequence', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("entity_kind = 'SALE_LOT'", name=op.f('ck_sale_lots_sale_lot_kind')),
    sa.CheckConstraint('lot_sequence > 0', name=op.f('ck_sale_lots_positive_lot_sequence')),
    sa.ForeignKeyConstraint(['bond_id'], ['canonical_v2.bonds.bond_id'], name=op.f('fk_sale_lots_bond_id_bonds')),
    sa.ForeignKeyConstraint(['sale_lot_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_sale_lot_entity_kind'),
    sa.PrimaryKeyConstraint('sale_lot_id', name=op.f('pk_sale_lots')),
    sa.UniqueConstraint('bond_id', 'trading_market_raw', 'information_date', 'lot_sequence', name='sale_lot_natural_key'),
    schema='canonical_v2'
    )
    op.create_index('ix_sale_lots_bond', 'sale_lots', ['bond_id'], unique=False, schema='canonical_v2')
    op.create_table('source_field_assertions',
    sa.Column('assertion_id', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('source_column', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('mapping_category', sa.String(length=48), nullable=False),
    sa.Column('target_semantic_key', sa.Text(), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('transformation_rule', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['canonical_v2.source_records.source_record_id'], name=op.f('fk_source_field_assertions_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('assertion_id', name=op.f('pk_source_field_assertions')),
    sa.UniqueConstraint('source_record_id', 'source_column', 'mapping_category', name='source_field_assertion_identity'),
    schema='canonical_v2'
    )
    op.create_index('ix_source_field_assertions_record', 'source_field_assertions', ['source_record_id'], unique=False, schema='canonical_v2')
    op.create_table('source_record_entities',
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), nullable=False),
    sa.Column('provenance_role', sa.String(length=32), server_default=sa.text("'DESCRIBES'"), nullable=False),
    sa.CheckConstraint("entity_kind IN ('FINANCIAL_PRODUCT', 'FUND_SHARE_CLASS', 'SALE_LOT')", name=op.f('ck_source_record_entities_evidence_bearing_kind')),
    sa.CheckConstraint("provenance_role IN ('DESCRIBES', 'SUPPORTS')", name=op.f('ck_source_record_entities_provenance_role_allowed')),
    sa.ForeignKeyConstraint(['entity_id', 'entity_kind'], ['canonical_v2.canonical_entities.entity_id', 'canonical_v2.canonical_entities.entity_kind'], name='fk_source_record_entity_kind'),
    sa.ForeignKeyConstraint(['source_record_id'], ['canonical_v2.source_records.source_record_id'], name=op.f('fk_source_record_entities_source_record_id_source_records')),
    sa.PrimaryKeyConstraint('source_record_id', 'entity_id', name=op.f('pk_source_record_entities')),
    schema='canonical_v2'
    )
    op.create_index('ix_source_record_entities_entity', 'source_record_entities', ['entity_id'], unique=False, schema='canonical_v2')
    op.create_index('uq_source_record_entities_one_describes', 'source_record_entities', ['source_record_id'], unique=True, schema='canonical_v2', postgresql_where=sa.text("provenance_role = 'DESCRIBES'"))
    op.create_table('fact_evidence_links',
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('assertion_id', sa.Text(), nullable=False),
    sa.Column('evidence_role', sa.String(length=24), server_default=sa.text("'SUPPORTS'"), nullable=False),
    sa.CheckConstraint("evidence_role IN ('SUPPORTS', 'CONTRADICTS', 'DERIVES')", name=op.f('ck_fact_evidence_links_evidence_role_allowed')),
    sa.ForeignKeyConstraint(['assertion_id'], ['canonical_v2.source_field_assertions.assertion_id'], name=op.f('fk_fact_evidence_links_assertion_id_source_field_assertions')),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_v2.canonical_facts.fact_id'], name=op.f('fk_fact_evidence_links_fact_id_canonical_facts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', 'assertion_id', name=op.f('pk_fact_evidence_links')),
    schema='canonical_v2'
    )
    op.create_table('source_classification_values',
    sa.Column('source_classification_value_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assertion_id', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('candidate_concept_iri', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.String(length=24), nullable=False),
    sa.Column('resolution_rule', sa.Text(), nullable=True),
    sa.CheckConstraint("resolution_status IN ('RESOLVED', 'AMBIGUOUS', 'UNRESOLVED')", name=op.f('ck_source_classification_values_resolution_status_allowed')),
    sa.ForeignKeyConstraint(['assertion_id'], ['canonical_v2.source_field_assertions.assertion_id'], name=op.f('fk_source_classification_values_assertion_id_source_field_assertions')),
    sa.ForeignKeyConstraint(['candidate_concept_iri'], ['canonical_v2.ontology_concepts.concept_iri'], name=op.f('fk_source_classification_values_candidate_concept_iri_ontology_concepts')),
    sa.PrimaryKeyConstraint('source_classification_value_id', name=op.f('pk_source_classification_values')),
    sa.UniqueConstraint('assertion_id', 'raw_value', name='source_classification_value_identity'),
    schema='canonical_v2'
    )
    op.bulk_insert(
        sa.table(
            "product_types",
            sa.column("product_type_code", sa.String()),
            sa.column("label", sa.Text()),
            sa.column("ontology_iri", sa.Text()),
            schema="canonical_v2",
        ),
        [
            {"product_type_code": "ETF", "label": "Exchange Traded Fund", "ontology_iri": "https://miraeasset.com/ontology/financial-product#ETF"},
            {"product_type_code": "ETN", "label": "Exchange Traded Note", "ontology_iri": "https://miraeasset.com/ontology/financial-product#ETN"},
            {"product_type_code": "BOND", "label": "Bond", "ontology_iri": "https://miraeasset.com/ontology/financial-product#Bond"},
            {"product_type_code": "FUND", "label": "Fund", "ontology_iri": "https://miraeasset.com/ontology/financial-product#Fund"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "identifier_schemes",
            sa.column("scheme_code", sa.String()),
            sa.column("label", sa.Text()),
            sa.column("default_namespace", sa.Text()),
            sa.column("is_globally_unique", sa.Boolean()),
            schema="canonical_v2",
        ),
        [
            {"scheme_code": "SOURCE_ID", "label": "Source identifier", "default_namespace": "source", "is_globally_unique": False},
            {"scheme_code": "ISIN", "label": "International Securities Identification Number", "default_namespace": "iso-6166", "is_globally_unique": True},
            {"scheme_code": "TICKER", "label": "Exchange ticker", "default_namespace": "exchange", "is_globally_unique": False},
            {"scheme_code": "RIC", "label": "Reuters Instrument Code", "default_namespace": "refinitiv", "is_globally_unique": True},
            {"scheme_code": "LIPPER_ID", "label": "Lipper identifier", "default_namespace": "lipper", "is_globally_unique": True},
            {"scheme_code": "MA_ID", "label": "Mirae Asset identifier", "default_namespace": "miraeasset", "is_globally_unique": True},
            {"scheme_code": "KSD_ID", "label": "Korea Securities Depository identifier", "default_namespace": "ksd", "is_globally_unique": True},
            {"scheme_code": "REPRESENTATIVE_KSD_ID", "label": "Representative KSD fund identifier", "default_namespace": "ksd", "is_globally_unique": True},
            {"scheme_code": "FSS_ID", "label": "Financial Supervisory Service identifier", "default_namespace": "fss", "is_globally_unique": True},
        ],
    )
    op.bulk_insert(
        sa.table(
            "metric_definitions",
            sa.column("metric_code", sa.String()),
            sa.column("canonical_field", sa.Text()),
            sa.column("label", sa.Text()),
            sa.column("cross_source_comparable", sa.Boolean()),
            sa.column("filter_enabled", sa.Boolean()),
            sa.column("sort_enabled", sa.Boolean()),
            schema="canonical_v2",
        ),
        [
            {
                "metric_code": "AUM",
                "canonical_field": "product.aum",
                "label": "Assets under management",
                "cross_source_comparable": False,
                "filter_enabled": False,
                "sort_enabled": False,
            },
            {
                "metric_code": "EXPENSE_RATIO",
                "canonical_field": "product.expense_ratio",
                "label": "Expense ratio",
                "cross_source_comparable": False,
                "filter_enabled": False,
                "sort_enabled": False,
            },
        ],
    )
    op.bulk_insert(
        sa.table(
            "schema_versions",
            sa.column("component", sa.String()),
            sa.column("version", sa.String()),
            schema="canonical_v2",
        ),
        [{"component": "canonical_data_model", "version": "m10.8-a-canonical-v2"}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_classification_values', schema='canonical_v2')
    op.drop_table('fact_evidence_links', schema='canonical_v2')
    op.drop_index('uq_source_record_entities_one_describes', table_name='source_record_entities', schema='canonical_v2', postgresql_where=sa.text("provenance_role = 'DESCRIBES'"))
    op.drop_index('ix_source_record_entities_entity', table_name='source_record_entities', schema='canonical_v2')
    op.drop_table('source_record_entities', schema='canonical_v2')
    op.drop_index('ix_source_field_assertions_record', table_name='source_field_assertions', schema='canonical_v2')
    op.drop_table('source_field_assertions', schema='canonical_v2')
    op.drop_index('ix_sale_lots_bond', table_name='sale_lots', schema='canonical_v2')
    op.drop_table('sale_lots', schema='canonical_v2')
    op.drop_table('quarantine_records', schema='canonical_v2')
    op.drop_index('ix_organization_relations_target', table_name='organization_relations', schema='canonical_v2')
    op.drop_table('organization_relations', schema='canonical_v2')
    op.drop_index('ix_metric_observations_subject_metric_date', table_name='metric_observations', schema='canonical_v2')
    op.drop_index('ix_metric_observations_metric_numeric', table_name='metric_observations', schema='canonical_v2')
    op.drop_table('metric_observations', schema='canonical_v2')
    op.drop_index('ix_index_relations_target', table_name='index_relations', schema='canonical_v2')
    op.drop_table('index_relations', schema='canonical_v2')
    op.drop_table('identity_resolution_cases', schema='canonical_v2')
    op.drop_index('ix_fund_share_classes_parent', table_name='fund_share_classes', schema='canonical_v2')
    op.drop_table('fund_share_classes', schema='canonical_v2')
    op.drop_table('fact_conflict_cases', schema='canonical_v2')
    op.drop_index('uq_entity_identifiers_validated_global', table_name='entity_identifiers', schema='canonical_v2', postgresql_where=sa.text("validation_status = 'VALIDATED' AND conflict_status = 'NONE'"))
    op.drop_index('ix_entity_identifiers_lookup', table_name='entity_identifiers', schema='canonical_v2')
    op.drop_table('entity_identifiers', schema='canonical_v2')
    op.drop_index('ix_entity_classifications_concept', table_name='entity_classifications', schema='canonical_v2')
    op.drop_table('entity_classifications', schema='canonical_v2')
    op.drop_index('ix_entity_aliases_lookup', table_name='entity_aliases', schema='canonical_v2')
    op.drop_table('entity_aliases', schema='canonical_v2')
    op.drop_table('source_records', schema='canonical_v2')
    op.drop_table('ingestion_runs', schema='canonical_v2')
    op.drop_table('funds', schema='canonical_v2')
    op.drop_table('exchange_traded_products', schema='canonical_v2')
    op.drop_table('canonical_facts', schema='canonical_v2')
    op.drop_table('bonds', schema='canonical_v2')
    op.drop_table('organizations', schema='canonical_v2')
    op.drop_table('indices', schema='canonical_v2')
    op.drop_table('identifier_collision_cases', schema='canonical_v2')
    op.drop_index('ix_financial_products_type', table_name='financial_products', schema='canonical_v2')
    op.drop_table('financial_products', schema='canonical_v2')
    op.drop_table('entity_id_crosswalk', schema='canonical_v2')
    op.drop_index('ix_dataset_snapshots_dataset_date', table_name='dataset_snapshots', schema='canonical_v2')
    op.drop_table('dataset_snapshots', schema='canonical_v2')
    op.drop_table('source_datasets', schema='canonical_v2')
    op.drop_table('schema_versions', schema='canonical_v2')
    op.drop_table('product_types', schema='canonical_v2')
    op.drop_index('ix_ontology_concepts_category', table_name='ontology_concepts', schema='canonical_v2')
    op.drop_table('ontology_concepts', schema='canonical_v2')
    op.drop_table('metric_definitions', schema='canonical_v2')
    op.drop_table('identifier_schemes', schema='canonical_v2')
    op.drop_index('ix_canonical_entities_normalized_name', table_name='canonical_entities', schema='canonical_v2')
    op.drop_index('ix_canonical_entities_kind', table_name='canonical_entities', schema='canonical_v2')
    op.drop_table('canonical_entities', schema='canonical_v2')
    op.execute(sa.schema.DropSchema("canonical_v2"))
    # ### end Alembic commands ###
